// GENERATED by scripts/chrome_bridge.py. Local secret, never commit.
// If you change the port, reload the extension in chrome://extensions.
self.HP_BRIDGE = { port: 8947, token: "677a4ff6af6ae2065ae24756bd2654b8166fd5c1351fe09e" };
