// GENERATED by scripts/chrome_bridge.py from scripts/dom_helpers.js,
// scripts/dom_thread_list.js and scripts/dom_extract_thread.js. Edit those, not this.
self.__hpLib = Object.assign(
(// Small page operations used by fetch_instagram_dms.py, next to dom_thread_list.js
// and dom_extract_thread.js. One object literal so both browser drivers can load
// it: the DevTools driver evaluates it, the Chrome extension bundles it.
// Read-only apart from scrolling and clicking an inbox tab or a thread row.
({
  // Is any of these selectors on the page right now?
  hasAny: (selectors) => selectors.some(s => !!document.querySelector(s)),

  location: () => location.href,

  // Click the Primary / General inbox tab. Never anything else.
  clickTab: (label) => {
    const tab = [...document.querySelectorAll('[role="tab"]')]
      .find(t => (t.innerText || "").trim().startsWith(label));
    if (!tab) return false;
    tab.click();
    return true;
  },

  // Scroll the thread list down by most of a screen. False when it cannot move.
  scrollList: () => {
    const list = document.querySelector('[aria-label="Thread list"]') || document.body;
    for (const e of [list, ...list.querySelectorAll("div")]) {
      const oy = getComputedStyle(e).overflowY;
      if ((oy === "auto" || oy === "scroll") && e.scrollHeight > e.clientHeight + 4 &&
          e.querySelector('[role="button"]')) {
        const before = e.scrollTop;
        e.scrollTop = before + e.clientHeight * 0.8;
        return e.scrollTop !== before;
      }
    }
    return false;
  },

  // Click the list row with this name and preview. Never anything else.
  clickRow: ([name, preview]) => {
    const list = document.querySelector('[aria-label="Thread list"]') || document.body;
    const rows = [...list.querySelectorAll('[role="button"]')].filter(b =>
      [...b.querySelectorAll("[aria-label]")].some(e => / ago$|^just now$/i.test(e.getAttribute("aria-label") || "")));
    const norm = s => (s || "").replace(/\s+/g, " ").trim();
    const row = rows.find(b => {
      const t = norm(b.innerText);
      return t.includes(norm(name)) && t.includes(norm(preview).slice(0, 40));
    });
    if (!row) return false;
    row.scrollIntoView({ block: "center" });
    row.click();
    return true;
  },

  // Scroll the open thread's message pane up (towards older messages).
  scrollHistory: () => {
    const r = document.querySelector('[aria-label^="React to message from"]');
    if (!r) return false;
    for (let e = r.parentElement; e; e = e.parentElement) {
      const oy = getComputedStyle(e).overflowY;
      if (oy === "scroll" || oy === "auto") {
        const before = e.scrollTop;
        e.scrollTop = before - 4000;
        return e.scrollTop !== before;
      }
    }
    return false;
  },
})
),
{
listRows: (// Reads the visible rows of the Instagram web inbox thread list.
// Evaluated in the page by fetch_instagram_dms.py. Read-only: it never clicks.
//
// Returns one entry per rendered row with the display name, the preview line,
// Instagram's own "N hours ago" label and every signal that could mean unread.
// Unread detection is deliberately generous: a false "unread" only delays a
// thread to the next run, a false "read" would mark the lead's message Seen.
() => {
  const list = document.querySelector('[aria-label="Thread list"]') || document.body;
  const rows = [...list.querySelectorAll('[role="button"]')].filter(b => {
    const labels = [...b.querySelectorAll("[aria-label]")].map(e => e.getAttribute("aria-label"));
    return labels.some(l => / ago$|^just now$/i.test(l || ""));
  });

  const out = rows.map((b, index) => {
    const ageLabel = [...b.querySelectorAll("[aria-label]")]
      .map(e => e.getAttribute("aria-label"))
      .find(l => / ago$|^just now$/i.test(l || "")) || "";
    const lines = (b.innerText || "").split("\n").map(s => s.trim())
      .filter(s => s && s !== "·" && !/^\d+\s*[smhdwy]$/.test(s) && !/^Active( now|\s.*ago)?$/.test(s));
    const name = lines[0] || "";
    const preview = lines.slice(1).join(" ");

    const leaves = [...b.querySelectorAll("span,div")]
      .filter(e => e.childElementCount === 0 && (e.textContent || "").trim());
    const boldLeaves = leaves.filter(e => parseInt(getComputedStyle(e).fontWeight, 10) >= 600)
      .map(e => e.textContent.trim().slice(0, 20));
    const unreadLabel = [...b.querySelectorAll("[aria-label]")]
      .some(e => /unread/i.test(e.getAttribute("aria-label") || ""));
    const dots = [...b.querySelectorAll("div,span")].filter(e => {
      if (e.childElementCount || (e.textContent || "").trim()) return false;
      const s = getComputedStyle(e);
      const w = parseFloat(s.width), h = parseFloat(s.height);
      const rgb = (s.backgroundColor.match(/\d+(\.\d+)?/g) || []).map(Number);
      // Instagram's unread dot is blue. The green "active now" dot on avatars is not unread.
      const blue = rgb.length >= 3 && (rgb[3] === undefined || rgb[3] > 0) &&
        rgb[2] > 150 && rgb[2] > rgb[0] + 60;
      return w >= 6 && w <= 14 && Math.abs(w - h) < 1 && s.borderRadius !== "0px" && blue;
    }).map(e => getComputedStyle(e).backgroundColor);

    return {
      index, name, preview, ageLabel,
      unread: boldLeaves.length > 0 || unreadLabel || dots.length > 0,
      unreadSignals: { boldLeaves, unreadLabel, dots },
    };
  });

  let scroller = null;
  for (const e of [list, ...list.querySelectorAll("div")]) {
    const oy = getComputedStyle(e).overflowY;
    if ((oy === "auto" || oy === "scroll") && e.scrollHeight > e.clientHeight + 4 &&
        e.querySelector('[role="button"]')) { scroller = e; break; }
  }
  const account = (document.querySelector('[aria-label="Thread list"] [role="button"]') || {}).innerText || "";
  return {
    url: location.href,
    account: account.split("\n")[0].trim(),
    rows: out,
    atEnd: scroller ? scroller.scrollTop + scroller.clientHeight >= scroller.scrollHeight - 4 : true,
    hasScroller: !!scroller,
  };
}
),
extractThread: (// Reads the currently open Instagram web DM thread straight from the DOM.
// Evaluated in the page by fetch_instagram_dms.py. Returns plain JSON.
//
// How the sender is known: every message bubble, attachments and contact cards
// included, carries hidden action buttons labelled
// "React to message from <username>". Walking the message pane in document
// order, everything seen since the previous such label belongs to the message
// that label closes. Nothing is inferred from bubble colour or position.
() => {
  const REACT = /^React to message from (.+)$/;
  const ACTION = /^(React to|Reply to|See more options for) message from /;
  const TS = [
    /^\d{1,2} [A-Z][a-z]{2} \d{4}, \d{1,2}:\d{2}$/,   // 23 Aug 2026, 17:45
    /^(Mon|Tue|Wed|Thu|Fri|Sat|Sun) \d{1,2}:\d{2}$/,    // Mon 18:50
    /^\d{1,2}:\d{2}$/,                                   // 05:48, today
    /^(Yesterday|Today),? (at )?\d{1,2}:\d{2}$/i,
  ];
  const NOISE = new Set([
    "seen", "new messages", "enter", "typing...", "active now", "edited",
    "whatsapp message", "whatsapp call", "view profile",
  ]);
  const PROFILE_LABEL = "Open the profile page of ";

  const header = document.querySelector('a[aria-label^="' + PROFILE_LABEL + '"]');
  const threadHandle = header
    ? header.getAttribute("aria-label").slice(PROFILE_LABEL.length).trim()
    : null;
  const requestBanner = [...document.querySelectorAll('[role="button"],button')]
    .some(b => /^(Accept|Delete|Block)$/.test((b.innerText || "").trim()));

  const firstReact = document.querySelector('[aria-label^="React to message from"]');
  let scroller = null;
  if (firstReact) {
    for (let e = firstReact.parentElement; e; e = e.parentElement) {
      const oy = getComputedStyle(e).overflowY;
      if (oy === "scroll" || oy === "auto") { scroller = e; break; }
    }
  }
  if (!scroller) {
    return { ok: false, reason: firstReact ? "no scroll container" : "no messages rendered",
             threadHandle, url: location.href, requestBanner, messages: [] };
  }

  const walker = document.createTreeWalker(
    scroller, NodeFilter.SHOW_ELEMENT | NodeFilter.SHOW_TEXT);
  const messages = [];
  let currentTs = null;
  let parts = [];
  let reachedStart = false;
  let node;

  while ((node = walker.nextNode())) {
    if (node.nodeType === Node.ELEMENT_NODE) {
      const tag = node.tagName.toLowerCase();
      const inProfileLink = !!node.closest('a[aria-label^="' + PROFILE_LABEL + '"]');
      if (tag === "a" && !inProfileLink) {
        const href = (node.getAttribute("href") || "").split("?")[0];
        let m;
        if ((m = href.match(/^\/(reel|reels|p|stories)\/[^/]+/))) {
          parts.push({ kind: "media", text: "[shared " + (m[1] === "p" ? "post" : m[1].replace(/s$/, "")) + " https://www.instagram.com" + href + "]" });
        } else if ((m = href.match(/^\/([A-Za-z0-9._]{1,40})\/$/)) && !node.getAttribute("aria-label")) {
          parts.push({ kind: "share", user: m[1] });
        }
      } else if (tag === "video") {
        parts.push({ kind: "media", text: "[video]" });
      } else if (tag === "audio") {
        parts.push({ kind: "media", text: "[voice message]" });
      } else if (tag === "img" && !inProfileLink && node.closest('[role="presentation"]')) {
        parts.push({ kind: "media", text: "[image]" });
      }

      const label = node.getAttribute("aria-label");
      if (!label) continue;
      const m = label.match(REACT);
      if (!m || node.parentElement.closest('[aria-label^="React to message from"]')) continue;

      const shares = parts.filter(p => p.kind === "share").map(p => p.user);
      let lines = parts.filter(p => p.kind === "text").map(p => p.text)
        .filter(t => !shares.includes(t));
      const media = [...new Set(parts.filter(p => p.kind === "media").map(p => p.text))];
      if (shares.length) media.unshift("[shared post from @" + shares[0] + "]");
      // A shared reel already names its link; a bare [image] beside it is the thumbnail.
      const hasShare = media.some(t => t.startsWith("[shared"));
      const mediaOut = hasShare ? media.filter(t => t !== "[image]" && t !== "[video]") : media;
      if (!lines.length && !mediaOut.length) lines = ["[attachment]"];

      messages.push({
        sender: m[1].trim(),
        timestamp_label: currentTs,
        text: mediaOut.concat(lines).join("\n"),
        reply_context: parts.filter(p => p.kind === "reply_marker" || p.kind === "reply_context")
          .map(p => p.text).join(" / "),
      });
      parts = [];
      continue;
    }

    const raw = (node.textContent || "").trim();
    if (!raw) continue;
    const el = node.parentElement;
    if (!el || el.closest("svg")) continue;
    if (ACTION.test(raw)) continue;
    if (raw === "View Profile" || / · Instagram$/.test(raw)) {
      // Profile card that Instagram renders above the first message of a thread.
      parts = [];
      reachedStart = true;
      continue;
    }
    if (NOISE.has(raw.toLowerCase())) continue;
    if (TS.some(r => r.test(raw))) { currentTs = raw; continue; }
    if (/ replied to /i.test(raw)) { parts.push({ kind: "reply_marker", text: raw }); continue; }
    const inBubble = !!el.closest('[role="presentation"]');
    if (!inBubble && parts.some(p => p.kind === "reply_marker")) {
      parts.push({ kind: "reply_context", text: raw });
      continue;
    }
    parts.push({ kind: "text", text: raw });
  }

  return {
    ok: true,
    url: location.href,
    threadHandle,
    requestBanner,
    reachedStart,
    scrollTop: scroller.scrollTop,
    scrollHeight: scroller.scrollHeight,
    clientHeight: scroller.clientHeight,
    messages,
  };
}
),
});
