#!/usr/bin/env python3
"""
build_dashboard_data.py -- feeds the standalone dashboard from the workbook.

Reads master/hp-insta-leads.xlsx and writes lead-dashboard-data.js, which
lead-dashboard.html loads with a plain script tag. A script tag works from
file:// where fetch() does not, so the dashboard opens by double-clicking the
HTML with no server and no build step.

Run this after every upsert so the dashboard matches the source of truth.

Usage:
    python scripts/build_dashboard_data.py [--workbook master/hp-insta-leads.xlsx]
                                           [-o lead-dashboard-data.js]
"""

import argparse
import json
import os
import sys
from datetime import datetime, date

from openpyxl import load_workbook

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
DEFAULT_WORKBOOK = os.path.join(ROOT, "master", "hp-insta-leads.xlsx")
DEFAULT_OUTPUT = os.path.join(ROOT, "lead-dashboard-data.js")

SHEET_KEYS = {
    "Overview": "overview",
    "Leads": "leads",
    "Daily Activity": "daily",
    "Weekly Activity": "weekly",
    "Changelog": "changelog",
    "Messages": "messages",
    "Run Log": "runs",
}


def cell_value(value):
    if value is None:
        return ""
    if isinstance(value, (datetime, date)):
        return value.strftime("%Y-%m-%d")
    if isinstance(value, bool):
        return "yes" if value else "no"
    return value


def read_sheet(sheet):
    header = [cell_value(c.value) for c in sheet[1]]
    rows = []
    for raw in sheet.iter_rows(min_row=2, values_only=True):
        if all(v in (None, "") for v in raw):
            continue
        rows.append({header[i]: cell_value(raw[i])
                     for i in range(min(len(header), len(raw)))})
    return rows


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--workbook", default=DEFAULT_WORKBOOK)
    parser.add_argument("-o", "--output", default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    if not os.path.isfile(args.workbook):
        print("ERROR: no workbook at %s, run the upsert first" % args.workbook,
              file=sys.stderr)
        return 1

    workbook = load_workbook(args.workbook, data_only=True)
    payload = {
        "generated_at": datetime.now().isoformat(timespec="seconds"),
        "workbook": os.path.basename(args.workbook),
        "workbook_modified": datetime.fromtimestamp(
            os.path.getmtime(args.workbook)).isoformat(timespec="seconds"),
    }
    for sheet_name, key in SHEET_KEYS.items():
        payload[key] = read_sheet(workbook[sheet_name]) \
            if sheet_name in workbook.sheetnames else []

    body = json.dumps(payload, indent=1, ensure_ascii=False)
    with open(args.output, "w", encoding="utf-8") as fh:
        fh.write("// Generated by scripts/build_dashboard_data.py. Do not edit.\n")
        fh.write("// Source: %s\n" % os.path.basename(args.workbook))
        fh.write("window.LEAD_DATA = %s;\n" % body)

    print("Wrote %s" % args.output)
    print("  %d leads | %d messages | %d changelog | %d runs | %d days | %d weeks"
          % (len(payload["leads"]), len(payload["messages"]),
             len(payload["changelog"]), len(payload["runs"]),
             len(payload["daily"]), len(payload["weekly"])))
    return 0


if __name__ == "__main__":
    sys.exit(main())
