/**
 * OAuth Routes — Authorization and token endpoints for MCP
 * 
 * Endpoints:
 * - GET /oauth/authorize — Authorization page (user approves/denies access)
 * - POST /oauth/token — Token exchange (authorization code → access token)
 * - POST /oauth/revoke — Token revocation (optional)
 * 
 * Supports OAuth 2.0 Authorization Code Flow with PKCE (optional)
 */

import express from 'express';
import { v4 as uuidv4 } from 'uuid';
import { logger } from '../logger.js';
import { generateTokenPair } from '../oauth/tokenGenerator.js';
import { validateAccessToken } from '../oauth/tokenValidator.js';
import validateToken from '../middleware/validateToken.js';
import { DynamoDBDocumentClient, PutCommand, GetCommand, DeleteCommand } from '@aws-sdk/lib-dynamodb';
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';

const router = express.Router();

// DynamoDB setup for storing authorization codes
const dynamoClient = new DynamoDBClient({ region: process.env.AWS_REGION || 'ap-south-1' });
const docClient = DynamoDBDocumentClient.from(dynamoClient);
const OAUTH_TABLE = process.env.OAUTH_CODES_TABLE_NAME || 'realtyflow-oauth-codes';
const OAUTH_CONNECTIONS_TABLE = process.env.OAUTH_CONNECTIONS_TABLE || 'realtyflow-oauth-connections';

// OAuth provider configurations
const OAUTH_PROVIDERS = {
  anthropic: {
    clientId: process.env.OAUTH_ANTHROPIC_CLIENT_ID,
    clientSecret: process.env.OAUTH_ANTHROPIC_CLIENT_SECRET,
    name: 'Claude',
    redirectUri: 'https://claude.ai/oauth/callback',
  },
  openai: {
    clientId: process.env.OAUTH_OPENAI_CLIENT_ID,
    clientSecret: process.env.OAUTH_OPENAI_CLIENT_SECRET,
    name: 'ChatGPT',
    redirectUri: 'https://chatgpt.com/oauth/callback',
  },
};

// Validate OAuth provider configuration
Object.entries(OAUTH_PROVIDERS).forEach(([key, config]) => {
  if (!config.clientId || !config.clientSecret) {
    logger.warn(`oauth.missing_credentials.${key}`, {
      hasClientId: !!config.clientId,
      hasClientSecret: !!config.clientSecret,
    });
  }
});

/**
 * Resolve the authenticated user for the OAuth authorization page.
 * Supports either a Bearer JWT (from validateToken) or a short-lived session
 * code generated by /api/ai-integrations/connect. Session codes are single-use
 * and expire after 5 minutes, allowing the browser redirect to remain
 * authenticated without leaking a JWT in the URL.
 */
async function resolveOAuthUser(req, res, next) {
  // Prefer a real JWT if the caller provided one.
  if (req.headers.authorization && req.headers.authorization.startsWith('Bearer ')) {
    return validateToken(req, res, next);
  }

  // Fall back to a single-use session code from the query (GET) or body (POST).
  const sessionCode = req.query?.session || req.body?.session;
  if (!sessionCode) {
    return res.status(401).json({ error: 'unauthorized', error_description: 'Authentication required' });
  }

  try {
    const result = await docClient.send(
      new GetCommand({
        TableName: OAUTH_TABLE,
        Key: { code: sessionCode },
      })
    );

    const session = result.Item;
    const nowSeconds = Math.floor(Date.now() / 1000);
    if (!session || session.type !== 'oauth_session' || session.expiresAt < nowSeconds) {
      return res.status(401).json({ error: 'unauthorized', error_description: 'Invalid or expired session' });
    }

    // Hydrate req.user so the rest of the authorization flow can use it.
    req.user = {
      userId: session.userId,
      tenantId: session.tenantId,
      name: session.userName || '',
      email: session.userEmail || '',
    };

    // Session codes are single-use.
    await docClient.send(
      new DeleteCommand({
        TableName: OAUTH_TABLE,
        Key: { code: sessionCode },
      })
    );

    next();
  } catch (err) {
    logger.error('oauth.resolve_session.error', { error: err.message });
    return res.status(500).json({ error: 'server_error', error_description: 'Failed to resolve session' });
  }
}

/**
 * GET /oauth/authorize
 * Authorization page where user approves/denies access.
 * Requires a valid user session (JWT) so the authorization can be bound to the
 * correct tenant. The token endpoint below remains public and is authenticated
 * via client credentials as required by OAuth 2.0.
 * 
 * Query params:
 * - client_id: 'anthropic' or 'openai'
 * - redirect_uri: Where to redirect after authorization
 * - scope: Requested scopes (space-separated)
 * - state: CSRF token (returned in redirect)
 * - session: Short-lived session code (when using browser redirect from SPA)
 */
router.get('/authorize', resolveOAuthUser, (req, res) => {
  try {
    const { client_id, redirect_uri, scope, state, session } = req.query;

    // Validate client_id
    if (!client_id || !OAUTH_PROVIDERS[client_id]) {
      logger.warn('oauth.authorize.invalid_client', { client_id });
      return res.status(400).json({ error: 'invalid_client', error_description: 'Unknown client_id' });
    }

    const provider = OAUTH_PROVIDERS[client_id];

    // Validate redirect_uri
    if (redirect_uri !== provider.redirectUri) {
      logger.warn('oauth.authorize.invalid_redirect_uri', { client_id, redirect_uri });
      return res.status(400).json({ error: 'invalid_request', error_description: 'Invalid redirect_uri' });
    }

    // User is authenticated by resolveOAuthUser (JWT or session code)
    const user = req.user;
    const tenantId = user.tenantId;
    if (!tenantId) {
      logger.warn('oauth.authorize.no_tenant', { userId: user.userId });
      return res.status(400).json({ error: 'invalid_request', error_description: 'User has no tenant' });
    }

    // Render authorization page
    res.render('oauth-authorize', {
      client_name: provider.name,
      client_id,
      scope: scope || '',
      state: state || '',
      redirect_uri,
      session: session || '',
      user: {
        name: user.name,
        email: user.email,
        tenantId,
      },
    });
  } catch (err) {
    logger.error('oauth.authorize.error', { error: err.message });
    res.status(500).json({ error: 'server_error', error_description: err.message });
  }
});

/**
 * POST /oauth/authorize
 * Process authorization approval/denial
 * 
 * Body:
 * - client_id: 'anthropic' or 'openai'
 * - redirect_uri: Where to redirect
 * - state: CSRF token
 * - action: 'allow' or 'deny'
 */
router.post('/authorize', resolveOAuthUser, async (req, res) => {
  try {
    const { client_id, redirect_uri, state, action } = req.body;

    // Validate inputs
    if (!client_id || !OAUTH_PROVIDERS[client_id]) {
      return res.status(400).json({ error: 'invalid_client' });
    }

    const user = req.user;
    const tenantId = user.tenantId;
    const userId = user.userId;

    // Handle denial
    if (action === 'deny') {
      const errorUrl = new URL(redirect_uri);
      errorUrl.searchParams.append('error', 'access_denied');
      errorUrl.searchParams.append('error_description', 'User denied authorization');
      errorUrl.searchParams.append('state', state);
      logger.info('oauth.authorize.denied', { client_id, userId, tenantId });
      return res.redirect(errorUrl.toString());
    }

    // Handle approval
    if (action === 'allow') {
      // Generate authorization code
      const authCode = uuidv4();
      const expiresAt = Date.now() + 10 * 60 * 1000; // 10 minutes

      // Store authorization code in DynamoDB
      await docClient.send(
        new PutCommand({
          TableName: OAUTH_TABLE,
          Item: {
            code: authCode,
            client_id,
            tenantId,
            userId,
            expiresAt,
            scope: 'read_leads write_leads read_properties write_properties read_owners write_owners read_tenants write_tenants read_buyers write_buyers read_meetings write_meetings',
            createdAt: new Date().toISOString(),
          },
        })
      );

      logger.info('oauth.authorize.approved', { client_id, userId, tenantId });

      // Redirect with authorization code
      const successUrl = new URL(redirect_uri);
      successUrl.searchParams.append('code', authCode);
      successUrl.searchParams.append('state', state);
      return res.redirect(successUrl.toString());
    }

    return res.status(400).json({ error: 'invalid_request', error_description: 'Invalid action' });
  } catch (err) {
    logger.error('oauth.authorize.post.error', { error: err.message });
    res.status(500).json({ error: 'server_error' });
  }
});

/**
 * POST /oauth/token
 * Exchange authorization code for access token
 * 
 * Body (application/x-www-form-urlencoded):
 * - grant_type: 'authorization_code' or 'refresh_token'
 * - code: Authorization code (for authorization_code grant)
 * - client_id: OAuth client ID
 * - client_secret: OAuth client secret
 * - refresh_token: Refresh token (for refresh_token grant)
 */
router.post('/token', async (req, res) => {
  try {
    const { grant_type, code, client_id, client_secret, refresh_token } = req.body;

    // Validate client credentials
    if (!client_id || !OAUTH_PROVIDERS[client_id]) {
      logger.warn('oauth.token.invalid_client', { client_id });
      return res.status(400).json({ error: 'invalid_client' });
    }

    const provider = OAUTH_PROVIDERS[client_id];
    if (client_secret !== provider.clientSecret) {
      logger.warn('oauth.token.invalid_secret', { client_id });
      return res.status(401).json({ error: 'invalid_client' });
    }

    // Authorization Code Grant
    if (grant_type === 'authorization_code') {
      if (!code) {
        return res.status(400).json({ error: 'invalid_request', error_description: 'code is required' });
      }

      // Retrieve authorization code from DynamoDB
      const result = await docClient.send(
        new GetCommand({
          TableName: OAUTH_TABLE,
          Key: { code },
        })
      );

      const authCodeItem = result.Item;
      if (!authCodeItem) {
        logger.warn('oauth.token.code_not_found', { code });
        return res.status(400).json({ error: 'invalid_code' });
      }

      // Check if code is expired
      if (authCodeItem.expiresAt < Date.now()) {
        logger.warn('oauth.token.code_expired', { code });
        return res.status(400).json({ error: 'invalid_code', error_description: 'Authorization code expired' });
      }

      // Check if code matches client_id
      if (authCodeItem.client_id !== client_id) {
        logger.warn('oauth.token.code_client_mismatch', { code, client_id });
        return res.status(400).json({ error: 'invalid_code' });
      }

      const { tenantId, userId, scope } = authCodeItem;

      // Generate tokens
      const tokenPair = generateTokenPair(userId, tenantId, scope.split(' '), client_id);

      // Delete authorization code (one-time use)
      await docClient.send(
        new DeleteCommand({
          TableName: OAUTH_TABLE,
          Key: { code },
        })
      );

      // Record the connection so the AI Integrations dashboard can list it.
      await docClient.send(
        new PutCommand({
          TableName: OAUTH_CONNECTIONS_TABLE,
          Item: {
            PK: `TENANT#${tenantId}#OAUTH_CLIENTS`,
            SK: `CLIENT#${client_id}`,
            clientId,
            clientName: OAUTH_PROVIDERS[client_id].name,
            status: 'connected',
            userId,
            tenantId,
            scopes: scope.split(' '),
            connectedAt: new Date().toISOString(),
            lastUsedAt: new Date().toISOString(),
          },
        })
      );

      logger.info('oauth.token.issued', { client_id, userId, tenantId });
      return res.json(tokenPair);
    }

    // Refresh Token Grant
    if (grant_type === 'refresh_token') {
      if (!refresh_token) {
        return res.status(400).json({ error: 'invalid_request', error_description: 'refresh_token is required' });
      }

      // Validate refresh token (note: we use JWT_SECRET here, but in production you might use JWT_REFRESH_SECRET)
      const { valid, decoded } = validateAccessToken(refresh_token);
      if (!valid || decoded.type !== 'refresh') {
        logger.warn('oauth.token.invalid_refresh_token');
        return res.status(401).json({ error: 'invalid_grant' });
      }

      const { tenantId, sub: userId, clientId: tokenClientId } = decoded;

      // Verify client_id matches
      if (tokenClientId !== client_id) {
        logger.warn('oauth.token.refresh_client_mismatch');
        return res.status(400).json({ error: 'invalid_client' });
      }

      // Generate new access token
      const tokenPair = generateTokenPair(userId, tenantId, ['read_leads', 'write_leads'], client_id);
      logger.info('oauth.token.refreshed', { client_id, userId, tenantId });
      return res.json(tokenPair);
    }

    return res.status(400).json({ error: 'unsupported_grant_type' });
  } catch (err) {
    logger.error('oauth.token.error', { error: err.message });
    res.status(500).json({ error: 'server_error' });
  }
});

/**
 * POST /oauth/revoke
 * Revoke an access token (optional endpoint)
 * 
 * Body:
 * - token: Token to revoke
 * - client_id: OAuth client ID
 * - client_secret: OAuth client secret
 */
router.post('/revoke', async (req, res) => {
  try {
    const { token, client_id, client_secret } = req.body;

    // Validate client credentials
    if (!client_id || !OAUTH_PROVIDERS[client_id]) {
      return res.status(400).json({ error: 'invalid_client' });
    }

    const provider = OAUTH_PROVIDERS[client_id];
    if (client_secret !== provider.clientSecret) {
      return res.status(401).json({ error: 'invalid_client' });
    }

    if (!token) {
      return res.status(400).json({ error: 'invalid_request' });
    }

    // In a production system, you would:
    // 1. Add token to a revocation list in DynamoDB
    // 2. Check this list during token validation
    // For now, we just acknowledge the revocation

    logger.info('oauth.revoke.requested', { client_id });
    res.status(200).json({ status: 'revoked' });
  } catch (err) {
    logger.error('oauth.revoke.error', { error: err.message });
    res.status(500).json({ error: 'server_error' });
  }
});

export default router;
