/**
 * Token Validation Middleware
 *
 * Validates Cognito user tokens for the /oauth/authorize endpoint.
 * Calls the auth microservice's /auth/me endpoint to verify the token
 * and get user context (userId, tenantId, name, email).
 *
 * Also supports session codes (short-lived codes generated by the CRM
 * backend's /api/ai-integrations/connect endpoint) for browser redirects.
 *
 * Claude Desktop flow (mcp-remote):
 *   mcp-remote opens the browser to /oauth/authorize with PKCE params but no
 *   session code. Rather than returning a 401 JSON (which the browser cannot
 *   act on), we redirect the browser to the RealtyFlow frontend so the user
 *   can log in and generate a session code via the AI Integrations page.
 */

import { Request, Response, NextFunction } from 'express';
import axios from 'axios';
import { logger } from '../utils/logger';
import { DynamoDBDocumentClient, GetCommand, DeleteCommand } from '@aws-sdk/lib-dynamodb';
import { DynamoDBClient } from '@aws-sdk/client-dynamodb';

const AUTH_SERVICE_URL = process.env.AUTH_SERVICE_URL || '';
const AWS_REGION = process.env.AWS_REGION || 'ap-south-1';
const OAUTH_TABLE = process.env.OAUTH_CODES_TABLE_NAME || 'realtyflow-oauth-codes';

// Frontend URL where unauthenticated OAuth authorize requests are redirected.
// On production this is the RealtyFlow app. On local dev it falls back to
// localhost so the desktop-session UI can still be reached.
const FRONTEND_URL = (process.env.FRONTEND_URL || '').replace(/\/$/, '');

const dynamoClient = new DynamoDBClient({ region: AWS_REGION });
const docClient = DynamoDBDocumentClient.from(dynamoClient);

export interface AuthenticatedUser {
  userId: string;
  tenantId: string;
  name: string;
  email: string;
}

declare global {
  namespace Express {
    interface Request {
      user?: AuthenticatedUser;
    }
  }
}

/**
 * Validate a Cognito JWT token by calling the auth microservice.
 */
async function validateCognitoToken(token: string): Promise<AuthenticatedUser | null> {
  if (!AUTH_SERVICE_URL) {
    logger.warn('validateToken.no_auth_service_url');
    return null;
  }

  try {
    const response = await axios.get(`${AUTH_SERVICE_URL}/auth/me`, {
      headers: { Authorization: `Bearer ${token}` },
      timeout: 5000,
    });

    const data = response.data;
    return {
      userId: data.userId || data.sub || data.id,
      tenantId: data.tenantId,
      name: data.name || data.displayName || '',
      email: data.email || '',
    };
  } catch (err: any) {
    logger.warn('validateToken.cognito_failed', { error: err.message });
    return null;
  }
}

/**
 * Build a safe redirect URL back to the frontend AI Integrations page so
 * the user can log in and approve the Claude Desktop (mcp-remote) OAuth flow.
 *
 * The full MCP /oauth/authorize URL (with all PKCE params) is base64url-encoded
 * and passed as `mcp_oauth_callback` so the frontend can reconstruct it after
 * the user authenticates and adds a session code.
 */
function buildLoginRedirectUrl(req: Request): string | null {
  if (!FRONTEND_URL) {
    logger.warn('validateToken.no_frontend_url', {
      reason: 'FRONTEND_URL environment variable is not set',
    });
    return null;
  }

  // Reconstruct the full OAuth authorize URL as seen by the browser.
  // OAUTH_BASE_URL is set in CloudFormation to the API Gateway invoke URL.
  const oauthBaseUrl = (process.env.OAUTH_BASE_URL || '').replace(/\/$/, '');
  if (!oauthBaseUrl) return null;

  const params = new URLSearchParams(req.query as Record<string, string>);
  const fullOAuthUrl = `${oauthBaseUrl}/oauth/authorize?${params.toString()}`;

  const loginRedirect =
    `${FRONTEND_URL}/crm/ai-integrations` +
    `?mcp_oauth_callback=${encodeURIComponent(fullOAuthUrl)}`;

  return loginRedirect;
}

/**
 * Resolve the authenticated user for the OAuth authorization page.
 * Supports either a Bearer JWT or a short-lived session code.
 *
 * Unauthenticated browser GET requests (Claude Desktop / mcp-remote) are
 * redirected to the RealtyFlow frontend instead of returning a bare 401.
 */
export async function resolveOAuthUser(req: Request, res: Response, next: NextFunction): Promise<void> {
  // Prefer a real JWT if the caller provided one
  if (req.headers.authorization && req.headers.authorization.startsWith('Bearer ')) {
    const token = req.headers.authorization.substring(7);
    const user = await validateCognitoToken(token);

    if (!user) {
      res.status(401).json({ error: 'unauthorized', error_description: 'Invalid token' });
      return;
    }

    req.user = user;
    next();
    return;
  }

  // Fall back to a single-use session code from the query (GET) or body (POST)
  const sessionCode = (req.query?.session as string) || req.body?.session;

  if (!sessionCode) {
    // For browser GET requests that carry PKCE params (mcp-remote / Claude Desktop),
    // redirect to the RealtyFlow frontend login page with the OAuth URL encoded.
    // This allows the user to log in and then return here with a valid session code.
    if (req.method === 'GET' && req.query.code_challenge) {
      const loginRedirect = buildLoginRedirectUrl(req);
      if (loginRedirect) {
        logger.info('validateToken.redirect_to_login', {
          client_id: req.query.client_id,
          redirect: loginRedirect.substring(0, 80) + '...',
        });
        res.redirect(302, loginRedirect);
        return;
      }
    }

    // No session code and no usable redirect target — return a structured 401.
    res.status(401).json({ error: 'unauthorized', error_description: 'Authentication required' });
    return;
  }

  try {
    const result = await docClient.send(
      new GetCommand({
        TableName: OAUTH_TABLE,
        Key: { code: sessionCode },
      })
    );

    const session = result.Item;
    const nowSeconds = Math.floor(Date.now() / 1000);
    if (!session || session.type !== 'oauth_session' || session.expiresAt < nowSeconds) {
      res.status(401).json({ error: 'unauthorized', error_description: 'Invalid or expired session' });
      return;
    }

    req.user = {
      userId: session.userId,
      tenantId: session.tenantId,
      name: session.userName || '',
      email: session.userEmail || '',
    };

    // Session codes are consumed only on the POST (final approval/denial)
    if (req.method === 'POST') {
      try {
        await docClient.send(
          new DeleteCommand({
            TableName: OAUTH_TABLE,
            Key: { code: sessionCode },
          })
        );
      } catch (deleteErr: any) {
        // Log but continue: the session was already validated. TTL will clean it up.
        logger.error('validateToken.session_delete_failed', {
          error: deleteErr.message,
          sessionCode: sessionCode.slice(0, 14) + '...',
        });
      }
    }

    next();
  } catch (err: any) {
    logger.error('validateToken.session_error', { error: err.message });
    res.status(500).json({ error: 'server_error', error_description: 'Failed to resolve session' });
  }
}
