"""
Browser drivers for fetch_instagram_dms.py.

Both expose the same small surface, so the fetch logic does not care which
Chrome it is reading:

    open(url)        open a reader tab on instagram.com/direct
    goto(url)        navigate it (instagram.com/direct only)
    call(fn, arg)    run one named helper from dom_helpers.js / dom_thread_list.js /
                     dom_extract_thread.js and return its JSON result
    url()            current address of the reader tab
    sleep(ms)
    close()

ExtensionDriver (default, browser_mode "extension")
    Uses the Chrome you already have open and logged in. The unpacked
    "HP Insta Lead Reader" extension in chrome-extension/ polls a tiny HTTP
    server this driver runs on 127.0.0.1 for the duration of a fetch. Commands
    are named helpers only, never free-form code, and each request carries a
    token that lives only in chrome-extension/bridge-config.js.

CdpDriver (browser_mode "cdp")
    The older path: a separate Chrome profile driven over the DevTools port with
    Playwright. Needs its own Instagram login.

    python scripts/chrome_bridge.py --build      # regenerate page_lib.js and the token file
    python scripts/chrome_bridge.py --check      # is the extension connected and Instagram logged in?
"""

import argparse
import http.server
import itertools
import json
import os
import queue
import re
import secrets
import socket
import subprocess
import sys
import threading
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
EXT_DIR = os.path.join(ROOT, "chrome-extension")
EXT_CONFIG = os.path.join(EXT_DIR, "bridge-config.js")
EXT_LIB = os.path.join(EXT_DIR, "page_lib.js")
CONFIG_PATH = os.path.join(ROOT, "config", "fetch-config.json")


class BridgeError(RuntimeError):
    pass


class ExtensionNotConnected(BridgeError):
    pass


def read_js(name):
    with open(os.path.join(HERE, name), encoding="utf-8") as fh:
        return fh.read().strip()


# ---------------------------------------------------------------- build

def build_page_lib():
    """chrome-extension/page_lib.js from the three DOM scripts. Rewritten only when it changed."""
    body = (
        "// GENERATED by scripts/chrome_bridge.py from scripts/dom_helpers.js,\n"
        "// scripts/dom_thread_list.js and scripts/dom_extract_thread.js. Edit those, not this.\n"
        "self.__hpLib = Object.assign(\n(%s\n),\n{\nlistRows: (%s\n),\nextractThread: (%s\n),\n});\n"
        % (read_js("dom_helpers.js"), read_js("dom_thread_list.js"), read_js("dom_extract_thread.js"))
    )
    old = None
    if os.path.isfile(EXT_LIB):
        with open(EXT_LIB, encoding="utf-8") as fh:
            old = fh.read()
    if old != body:
        with open(EXT_LIB, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(body)
        return True
    return False


def bridge_settings(port):
    """Token + port shared with the extension. The token is created once and kept."""
    token = None
    if os.path.isfile(EXT_CONFIG):
        with open(EXT_CONFIG, encoding="utf-8") as fh:
            text = fh.read()
        m = re.search(r'token:\s*"([0-9a-f]{32,})"', text)
        p = re.search(r"port:\s*(\d+)", text)
        if m and p and int(p.group(1)) == port:
            return port, m.group(1)
        token = m.group(1) if m else None
    token = token or secrets.token_hex(24)
    with open(EXT_CONFIG, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("// GENERATED by scripts/chrome_bridge.py. Local secret, never commit.\n"
                 "// If you change the port, reload the extension in chrome://extensions.\n"
                 'self.HP_BRIDGE = { port: %d, token: "%s" };\n' % (port, token))
    return port, token


# ---------------------------------------------------------------- extension driver

class _Server(http.server.ThreadingHTTPServer):
    daemon_threads = True
    allow_reuse_address = False


class ExtensionDriver:
    POLL_HOLD_SECONDS = 15

    def __init__(self, cfg, log):
        self.cfg = cfg
        self.log = log
        self.port, self.token = bridge_settings(int(cfg.get("bridge_port", 8947)))
        if build_page_lib():
            log("page_lib.js rebuilt from the DOM scripts")
        self.commands = queue.Queue()
        self.results = {}
        self.cond = threading.Condition()
        self.ids = itertools.count(1)
        self.last_poll = 0.0
        self.extension_version = None
        self.server = None

    # -- http side
    def _handler(driver):
        class Handler(http.server.BaseHTTPRequestHandler):
            def log_message(self, *a):
                pass

            def _deny(self):
                self.send_response(403)
                self.end_headers()

            def do_GET(self):
                if self.headers.get("X-HP-Token") != driver.token:
                    return self._deny()
                if not self.path.startswith("/next"):
                    self.send_response(404)
                    self.end_headers()
                    return
                driver.last_poll = time.time()
                m = re.search(r"[?&]v=([\w.]+)", self.path)
                driver.extension_version = m.group(1) if m else driver.extension_version
                try:
                    cmd = driver.commands.get(timeout=driver.POLL_HOLD_SECONDS)
                except queue.Empty:
                    self.send_response(204)
                    self.end_headers()
                    return
                data = json.dumps(cmd).encode("utf-8")
                self.send_response(200)
                self.send_header("Content-Type", "application/json")
                self.send_header("Content-Length", str(len(data)))
                self.end_headers()
                self.wfile.write(data)

            def do_POST(self):
                if self.headers.get("X-HP-Token") != driver.token or self.path != "/result":
                    return self._deny()
                length = int(self.headers.get("Content-Length") or 0)
                try:
                    body = json.loads(self.rfile.read(length).decode("utf-8"))
                except ValueError:
                    self.send_response(400)
                    self.end_headers()
                    return
                with driver.cond:
                    driver.results[body.get("id")] = body
                    driver.cond.notify_all()
                self.send_response(204)
                self.end_headers()
        return Handler

    def __enter__(self):
        try:
            self.server = _Server(("127.0.0.1", self.port), self._handler())
        except OSError as exc:
            raise BridgeError("port %d is busy (another fetch running?): %s" % (self.port, exc))
        threading.Thread(target=self.server.serve_forever, daemon=True).start()
        try:
            self._connect()
        except BaseException:
            self.server.shutdown()
            self.server.server_close()
            raise
        return self

    def __exit__(self, *exc):
        try:
            self._send("close", timeout=20)
        except BridgeError:
            pass
        if self.server:
            self.server.shutdown()
            self.server.server_close()

    def _connect(self):
        wait = int(self.cfg.get("extension_connect_wait_seconds", 90))
        self.log("waiting for the HP Insta Lead Reader extension in Chrome (up to %ds)" % wait)
        deadline = time.time() + wait
        launched = False
        while time.time() < deadline:
            try:
                reply = self._send("hello", timeout=max(5, min(40, deadline - time.time())))
                self.log("extension connected (v%s)" % reply.get("version"))
                return
            except BridgeError:
                pass
            if not launched and not chrome_running():
                # Chrome closed: start it with no window so the extension wakes up.
                self.log("Chrome is not running, starting it in the background")
                subprocess.Popen([self.cfg["chrome_path"], "--no-startup-window"],
                                 stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
                launched = True
        raise ExtensionNotConnected(
            "the extension did not connect. Is Chrome open with 'HP Insta Lead Reader' loaded "
            "and enabled in chrome://extensions? (setup: README section 12)")

    def _send(self, type_, timeout=60, **payload):
        cmd_id = next(self.ids)
        cmd = dict(payload, id=cmd_id, type=type_)
        self.commands.put(cmd)
        end = time.time() + timeout
        with self.cond:
            while cmd_id not in self.results:
                left = end - time.time()
                if left <= 0:
                    break
                self.cond.wait(left)
            res = self.results.pop(cmd_id, None)
        if res is None:
            # Pull it back if the extension never took it, so it is not run late.
            kept = []
            while True:
                try:
                    c = self.commands.get_nowait()
                except queue.Empty:
                    break
                if c["id"] != cmd_id:
                    kept.append(c)
            for c in kept:
                self.commands.put(c)
            raise BridgeError("no answer from the extension to %s within %ds" % (type_, timeout))
        if not res.get("ok"):
            raise BridgeError("%s failed in Chrome: %s" % (type_, res.get("error")))
        return res.get("value")

    # -- driver surface
    def open(self, url):
        self._send("open", url=url, windowState=self.cfg.get("extension_window_state", "minimized"), timeout=60)

    def goto(self, url):
        self._send("goto", url=url, timeout=60)

    def call(self, fn, arg=None):
        return self._send("call", fn=fn, arg=arg, timeout=60)

    def url(self):
        return self._send("url", timeout=20)

    def sleep(self, ms):
        time.sleep(ms / 1000.0)

    def close(self):
        self._send("close", timeout=20)


def chrome_running():
    try:
        out = subprocess.run(["tasklist", "/FI", "IMAGENAME eq chrome.exe", "/NH"],
                             capture_output=True, text=True, timeout=15).stdout
    except (OSError, subprocess.SubprocessError):
        return True
    return "chrome.exe" in out.lower()


# ---------------------------------------------------------------- DevTools driver

class CdpDriver:
    """Separate Chrome profile over the DevTools port (needs its own Instagram login)."""

    def __init__(self, cfg, log, keep_browser=False):
        self.cfg = cfg
        self.log = log
        self.keep_browser = keep_browser
        self.helpers = read_js("dom_helpers.js")
        self.scripts = {"listRows": read_js("dom_thread_list.js"),
                        "extractThread": read_js("dom_extract_thread.js")}
        self.proc = self.pw = self.browser = self.page = None

    def __enter__(self):
        from playwright.sync_api import sync_playwright
        self.proc = start_devtools_chrome(self.cfg)
        self.pw = sync_playwright().start()
        try:
            self.browser = self.pw.chromium.connect_over_cdp("http://127.0.0.1:%d" % self.cfg["devtools_port"])
        except Exception as exc:
            self.pw.stop()
            raise BridgeError("cannot attach to Chrome: %s" % exc)
        self.context = self.browser.contexts[0] if self.browser.contexts else self.browser.new_context()
        return self

    def __exit__(self, *exc):
        try:
            if self.page:
                self.page.close()
            if self.proc is not None and not self.keep_browser:
                self.browser.close()
        except Exception:
            pass
        self.pw.stop()

    def open(self, url):
        self.page = self.context.new_page()
        self.page.goto(url, wait_until="domcontentloaded")

    def goto(self, url):
        self.page.goto(url, wait_until="domcontentloaded")

    def call(self, fn, arg=None):
        if fn in self.scripts:
            return self.page.evaluate(self.scripts[fn])
        return self.page.evaluate("(arg) => (%s).%s(arg)" % (self.helpers, fn), arg)

    def url(self):
        return self.page.url

    def sleep(self, ms):
        self.page.wait_for_timeout(ms)

    def close(self):
        if self.page:
            self.page.close()
            self.page = None


def _port_open(port):
    with socket.socket() as s:
        s.settimeout(0.5)
        return s.connect_ex(("127.0.0.1", port)) == 0


def start_devtools_chrome(cfg):
    port = cfg["devtools_port"]
    if _port_open(port):
        return None
    profile = os.path.expandvars(cfg["chrome_profile_dir"])
    os.makedirs(profile, exist_ok=True)
    proc = subprocess.Popen([cfg["chrome_path"], "--remote-debugging-port=%d" % port,
                             "--user-data-dir=%s" % profile, "--no-first-run",
                             "--no-default-browser-check",
                             "--window-size=%s" % cfg.get("window_size", "1280,900"), "about:blank"],
                            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    for _ in range(60):
        if _port_open(port):
            return proc
        time.sleep(0.5)
    raise BridgeError("Chrome did not open DevTools port %d" % port)


def make_driver(cfg, log, mode=None, keep_browser=False):
    mode = mode or cfg.get("browser_mode", "extension")
    if mode == "extension":
        return ExtensionDriver(cfg, log)
    if mode == "cdp":
        return CdpDriver(cfg, log, keep_browser=keep_browser)
    raise BridgeError("unknown browser_mode %r" % mode)


def main():
    for stream in (sys.stdout, sys.stderr):
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")
        except (AttributeError, ValueError):
            pass
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--build", action="store_true", help="write chrome-extension/page_lib.js and bridge-config.js")
    ap.add_argument("--check", action="store_true", help="connect to the extension and check the Instagram login")
    args = ap.parse_args()
    with open(CONFIG_PATH, encoding="utf-8") as fh:
        cfg = json.load(fh)

    def log(msg):
        print("[bridge %s] %s" % (time.strftime("%H:%M:%S"), msg), flush=True)

    if args.build or not args.check:
        bridge_settings(int(cfg.get("bridge_port", 8947)))
        build_page_lib()
        log("extension files ready in %s" % EXT_DIR)
    if args.check:
        try:
            with ExtensionDriver(cfg, log) as drv:
                drv.open("https://www.instagram.com/direct/inbox/")
                ok = False
                for _ in range(25):
                    if drv.call("hasAny", ['[aria-label="Thread list"]']):
                        ok = True
                        break
                    drv.sleep(1000)
                listing = drv.call("listRows") if ok else {}
                log("instagram inbox %s; account %r; %d rows visible"
                    % ("visible" if ok else "NOT visible (logged out?)", listing.get("account"),
                       len(listing.get("rows", []))))
                return 0 if ok else 4
        except ExtensionNotConnected as exc:
            log(str(exc))
            return 7
        except BridgeError as exc:
            log(str(exc))
            return 5
    return 0


if __name__ == "__main__":
    sys.exit(main())
